export { default as HomeScreen } from './HomeScreen'
export { default as Screen1 } from './Screen1'
export { default as Screen2 } from './Screen2'
export { default as Screen3 } from './Screen3'
export { default as ScreenNews } from './ScreenNews'
export { default as SplashScreen } from './SplashScreen'
export { default as TestScreen } from './TestScreen'